/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/meal-log/': RouteRecordInfo<'/meal-log/', '/meal-log', Record<never, never>, Record<never, never>>,
    '/photo-ocr/': RouteRecordInfo<'/photo-ocr/', '/photo-ocr', Record<never, never>, Record<never, never>>,
    '/photo-pdf-ocr/': RouteRecordInfo<'/photo-pdf-ocr/', '/photo-pdf-ocr', Record<never, never>, Record<never, never>>,
    '/text-pdf-reader/': RouteRecordInfo<'/text-pdf-reader/', '/text-pdf-reader', Record<never, never>, Record<never, never>>,
  }
}
